#  Authors: Alexander Nanda, Levon Sarian, and Joseph Cruz
#  Improvements to be made:
#  1. PDF rag based upon Statlink DB
#  2. Recursive search for stats

import os
#import agentops

from crewai import Agent
from crewai import Crew
from crewai import Process
from crewai import Task
from langchain.agents import Tool
from langchain_openai import ChatOpenAI
from crewai_tools import SerperDevTool
from crewai_tools import SeleniumScrapingTool
from crewai_tools import YoutubeChannelSearchTool
from crewai_tools import WebsiteSearchTool
from langchain.agents import initialize_agent, load_tools
from langchain.chains import LLMChain
from langchain_community.utilities.dalle_image_generator import DallEAPIWrapper
from langchain_core.prompts import PromptTemplate
from langchain_openai import OpenAI
# from langchain_community.tools import SceneXplainTool
import os

'''p
arams = {
    "engine": "google",
    "gl": "us",
    "hl": "en",
}
search_tool = SerpAPIWrapper(params=params)
'''

search_tool = SerperDevTool() 
scraping_tool = SeleniumScrapingTool()
video_tool = YoutubeChannelSearchTool()
website_rag_tool = WebsiteSearchTool(website='https://247sports.com/')
#vision_tool = SceneXplainTool()
maxpreps_tool = WebsiteSearchTool(website='https://www.maxpreps.com/')
espn_tool = WebsiteSearchTool(website='https://www.espn.com/college-football/')
buckeyes_tool = WebsiteSearchTool(website='https://www.si.com/college/ohiostate/football')


# Player for the crew to run
playerInfo = """
First Name,Last Name,Sport,Position,Class,Ranking,Rating,Weight,Height,Total Likes
KJ,Bolden,Football,S,2024,9,5,190 lbs,6'2",4160
"""

json_report_validator = Agent(
  role='JSON Validator and creator',
  goal=f'Take all of the information passed to this agent and turn it into json fields for each category.', 
  backstory="Expert in turning text to json fields and outputting the final report in json format",
  tools=[],
  allow_delegation=True, 
  verbose=True, 
  memory = True,
)

master_report_gen = Agent(
  role='Master Report Generator',
  goal=f'Take all of the information passed back to this agent and create a well-formatted report that includes all of the in-depth reserach generated by each respective category.', 
  backstory="You are a expert reporter that specializes in generating in-depth reports",
  tools=[],
  allow_delegation=True, #might want to change this later
  verbose=True, 
  memory = True,
)

### Start of Summary Branch
## Basic Searching Loop

# Expert searcher based upon the given playerInfo. 

master_searcher = Agent(
  role='Master Basic Searcher Executor',
  goal=f'Find sports information online relevent to this specific player using their info: KJ,Bolden,Football',
  backstory="You are an expert in searching for specific information and statistics for particular sports players. You have been in this industry for 25 years and you recieve a tip for every relevant, informative, or interesting fact you find about a specific sports player",
  tools=[search_tool],
  allow_delegation=True,
  max_iter=10,
  memory = True,
)

# Search Query Agent

master_search_brancher = Agent(
  role='Master Search Query Brancher',
  goal=f'Take the search results from the Mark, Master Basic Search Executor and pass this information off to each of the Category Managers including Social Meida, Highlights, Stats, and Recursive for KJ,Bolden,Football',
  backstory="You are an expert in relaying information to other Agent Category Managers and give them basic search results so that each Manager can conduct in-depth reserach.",
  tools=[],
  allow_delegation=True,
  verbose=True, 
  max_iter=5,
  memory = True,
)
## End of basic searching loop

##Social Media Branch
# Social Presence and Posts Analyzer 
social_media_manager = Agent(
    role = 'Social Media Category Manager',
    goal = 'Using this info:KJ,Bolden,Football. First, delegate research tasks to each of the social media agents, then analyze the results to provide a comprehensive, evidence-backed, and in-depth summary of the player’s social media presence.',
    backstory="You are an expert in managing social media research agents and delegate research tasks to them. Additionally, after each research agent has completed their searches, you provide a comprehensive report back to the Master Report Generator.",
    tools=[], 
    verbose = True,
    memory = True, 
    max_iter=2,
    allow_delegation = True
)

# Social Media Stats and Trends Analyzer
social_media_stats_analyzer = Agent(
    role = 'Social Presence and Stats Analyzer',
    goal = 'Using this info KJ,Bolden,Football. Look at the athletes social media accounts and gather the aggregate views and stats across different platforms. Also find out if this player has any brand deals, nil, or sponsorships and finally give an estimate of their social media revenue' ,
    backstory="You are an expert social media analyzer. Using your tools you would navigate to specific athletes social media pages and analyze them. You create summarys based on the information from your goals",
    tools=[search_tool, scraping_tool], 
    verbose = True,
    memory = True, 
    max_iter=2,
    allow_delegation = True
)

# Social Media Posts Analyzer
social_media_posts_analyzer = Agent(
    role = 'Social Meda Posts Analyzer',
    goal = 'Using info KJ,Bolden,Football. Look at the athletes social media accounts use image recognition in order to find out what the athlete is posting about in order to generate a small summary of the athletes social media posts and them as a person',
    backstory="You are an expert in image recognition for social media and reports summaries on atheletes posts and generate great summaries and read into their social media posts to get a better understanding of them",
    # come back and get vision working
    tools=[search_tool, scraping_tool], 
    verbose = True,
    memory = True, 
    max_iter=2,
    allow_delegation = True
)

# Five Star Fans Consultor
five_star_fans_consultor = Agent(
    role = 'Five star fan consultor',
    goal = 'Using this info: KJ,Bolden,Football. You are a consultor who creates summaries for five star fans about an athlete that shows how good they are to be featured on five star fans ',
    backstory='You are consulting for five star fans, You aim to look for strategic partnerships that elevate the athletes, expand their brand, and enhance the fan opportunity to engage with their favorite teams ',
    tools=[search_tool, scraping_tool, video_tool], 
    verbose = True,
    memory = True, 
    max_iter=2,
    allow_delegation = True
)
## End of Social Media Branch


# Social Media Summary
social_summary = Task(
  description=f'Generate a comprehensive summary of social media information using all of the agents in the social media branch for this info: KJ,Bolden,Football. You must search the internet for information.',
  expected_output='You output an extremely comprehensive report that includes all of the research findings within the social media branch',
  agents=[social_media_posts_analyzer, social_media_stats_analyzer, five_star_fans_consultor, social_media_manager],
  context=[],
  async_execution=False,
)


# Overall Report 
information_accuracy_consultor = Agent(
    role = 'Information Accuracy Consultor',
    goal = 'Check over all the information generated by the master_report task. Make sure it is all accurate and if it is not remove it',
    backstory='You are an expert reviewer and fact checker for recruited athletes',
    tools=[search_tool], 
    verbose = True,
    memory = True, 
    max_iter=8,
    allow_delegation = True
)
master_report = Task(
  description=f'Generate a master report that is very detailed and long and includes all of the information from each of the category branches for this player: KJ Bolden. Refer to the information_accuracy_consultor to make sure all the information is correct',
  expected_output='You output JSON that includes all of the information from the comprehensive player summary ',
  agents=[social_media_manager, information_accuracy_consultor],
  context=[social_summary],
  async_execution=False,
)
# Writing task with language model configuration
output_validation = Task(
  description=f'Convert the final report into json, breaking each category into different fields for this player: KJ,Bolden',
  expected_output='You output JSON that includes all of the information from the comprehensive player summary report',
  agents=[json_report_validator],
  context=[master_report],
  async_execution=False,
  output_file='eval_timestamp.json'  
)

# Forming the tech-focused crew with enhanced configurations
crew = Crew(
    # may need to delete blockchain stuff???
  agents=[social_media_manager, social_media_posts_analyzer, social_media_stats_analyzer, five_star_fans_consultor, information_accuracy_consultor ],
  tasks=[social_summary, master_report, output_validation],
  manager_llm=ChatOpenAI(temperature=0, model="gpt-4-turbo"),
  # later return back to this and change again to be sure that the modoel is the best
  process=Process.hierarchical,
)
# Starting the task execution process with enhanced feedback
result = crew.kickoff()
print(result)
